import { notFound } from "next/navigation";
import { ContentCard, Metadata } from "@/components/ui/ContentCard";
import { ErrorSummary, Checkbox, Radio, SelectField, Textarea, TextField } from "@/components/ui/FormFields";
import { FilterControls } from "@/components/ui/FilterControls";
import { MediaFrame } from "@/components/ui/MediaFrame";
import { EditorialPage, StandardPage, TextPage, WideMediaPage } from "@/components/ui/PageLayouts";
import { Section } from "@/components/ui/Section";

export const dynamic = "force-dynamic";

export default function DesignSystemPage() {
  if (process.env.NODE_ENV === "production") notFound();
  return <StandardPage><div className="container"><Section as="div" spacing="editorial"><p className="eyebrow">Pyramid Designs · Phase 1B</p><h1 className="display m-0 mt-4">Shell and component review.</h1><p className="body-large text-measure mt-6 text-[var(--color-text-muted)]">Synthetic development-only content. This review route returns 404 in production.</p></Section>
    <Section aria-labelledby="layouts"><p className="eyebrow">Page layouts and media</p><h2 id="layouts" className="type-h2 m-0 mt-2">Composable shells, not generic templates.</h2><div className="mt-6 grid gap-[var(--grid-gap)] lg:grid-cols-3"><div className="surface p-5"><p className="caption">Standard page</p><StandardPage><p className="small">Page-width content</p></StandardPage></div><div className="surface p-5"><p className="caption">Editorial page</p><EditorialPage><p className="small">Measured reading column</p></EditorialPage></div><div className="surface p-5"><p className="caption">Wide media page</p><WideMediaPage><p className="small">Expanded visual field</p></WideMediaPage></div></div><MediaFrame className="mt-6" caption="Synthetic media-frame caption relationship."><div className="loading-block" aria-label="Synthetic media placeholder" /></MediaFrame></Section>
    <Section aria-labelledby="cards"><p className="eyebrow">Cards, metadata, filters</p><h2 id="cards" className="type-h2 m-0 mt-2">Neutral metadata with controlled emphasis.</h2><div className="mt-6"><FilterControls filters={["All work", "Brand", "Digital", "Editorial"]} selected="All work" /></div><div className="mt-6 grid gap-[var(--grid-gap)] lg:grid-cols-2"><ContentCard href="#project-example" media={<div className="loading-block" />} meta={<><Metadata>Brand</Metadata><Metadata>2026</Metadata></>} title="Synthetic project card" supporting="Clickable-card structure with media, metadata and supporting information." action="View"><span id="project-example" className="sr-only">Synthetic project destination</span></ContentCard><ContentCard href="#role-example" meta={<><Metadata>Design</Metadata><Metadata>Full time</Metadata></>} title="Synthetic role card" supporting="A second use of the same semantic card foundation." action="Details"><span id="role-example" className="sr-only">Synthetic role destination</span></ContentCard></div></Section>
    <Section aria-labelledby="forms"><p className="eyebrow">Native form primitives</p><h2 id="forms" className="type-h2 m-0 mt-2">Labels, help, errors and adequate targets.</h2><div className="mt-6 grid gap-[var(--grid-gap)] lg:grid-cols-2"><form className="surface grid gap-5 p-5" noValidate><ErrorSummary errors={[{ href: "#sample-email", message: "Enter a valid example email" }]} /><TextField id="sample-email" label="Email address" type="email" required helperText="Synthetic help text." error="Enter a valid example email." /><Textarea id="sample-message" label="Message" helperText="Synthetic textarea state." /><SelectField id="sample-topic" label="Topic" options={["Choose a topic", "Example option"]} /><Checkbox id="sample-consent" label="Example checkbox" /><Radio id="sample-radio" name="sample-choice" label="Example radio" /></form><div className="grid gap-4"><div className="loading-block" aria-label="Content loading placeholder" /><div className="empty-state"><p className="eyebrow">Empty state</p><h3 className="type-h3 m-0 mt-2">No synthetic results.</h3><p className="body m-0 mt-3 text-[var(--color-text-muted)]">A future page provides its approved recovery action.</p></div><div className="error-state"><p className="eyebrow">Error state</p><h3 className="type-h3 m-0 mt-2">Something needs another try.</h3><button className="button button-secondary mt-4" type="button">Try again</button></div></div></div></Section>
    <Section aria-labelledby="themes"><p className="eyebrow">Theme behaviour</p><h2 id="themes" className="type-h2 m-0 mt-2">System-aware, with no public toggle yet.</h2><div className="mt-6 grid gap-[var(--grid-gap)] lg:grid-cols-2"><div data-theme="light" className="surface p-5"><p className="caption">Light token preview</p><p className="type-h3 m-0 mt-2">Readable without JavaScript.</p></div><div data-theme="dark" className="surface p-5"><p className="caption">Dark token preview</p><p className="type-h3 m-0 mt-2">Future stored override supported.</p></div></div><p className="small mt-5 text-[var(--color-text-muted)]">Desktop navigation appears at 768px and above; the live header becomes a native-dialog mobile navigation below that point. Use browser device emulation to inspect the menu.</p></Section>
  </div></StandardPage>;
}
