import type { InputHTMLAttributes, ReactNode, SelectHTMLAttributes, TextareaHTMLAttributes } from "react";

type FieldBase = { id: string; label: string; helperText?: string; error?: string; required?: boolean };
type TextFieldProps = FieldBase & InputHTMLAttributes<HTMLInputElement>;
type TextareaProps = FieldBase & TextareaHTMLAttributes<HTMLTextAreaElement>;
type SelectProps = FieldBase & SelectHTMLAttributes<HTMLSelectElement> & { options: readonly string[] };
function Field({ id, label, helperText, error, required, children }: FieldBase & { children: ReactNode }) { return <div className="form-field"><label htmlFor={id}>{label}{required ? <span aria-hidden="true"> *</span> : null}</label>{children}{helperText ? <p id={`${id}-help`} className="small form-field__help">{helperText}</p> : null}{error ? <p id={`${id}-error`} className="small form-field__error">{error}</p> : null}</div>; }
function describedBy(id: string, helperText?: string, error?: string) { return [helperText ? `${id}-help` : null, error ? `${id}-error` : null].filter(Boolean).join(" ") || undefined; }
export function TextField({ id, label, helperText, error, required, ...props }: TextFieldProps) { return <Field id={id} label={label} helperText={helperText} error={error} required={required}><input id={id} className="form-control" required={required} aria-invalid={Boolean(error) || undefined} aria-describedby={describedBy(id, helperText, error)} {...props} /></Field>; }
export function Textarea({ id, label, helperText, error, required, ...props }: TextareaProps) { return <Field id={id} label={label} helperText={helperText} error={error} required={required}><textarea id={id} className="form-control" required={required} aria-invalid={Boolean(error) || undefined} aria-describedby={describedBy(id, helperText, error)} {...props} /></Field>; }
export function SelectField({ id, label, helperText, error, required, options, ...props }: SelectProps) { return <Field id={id} label={label} helperText={helperText} error={error} required={required}><select id={id} className="form-control" required={required} aria-invalid={Boolean(error) || undefined} aria-describedby={describedBy(id, helperText, error)} {...props}>{options.map((option) => <option key={option}>{option}</option>)}</select></Field>; }
export function Checkbox({ id, label, ...props }: InputHTMLAttributes<HTMLInputElement> & { id: string; label: string }) { return <label className="choice"><input id={id} type="checkbox" {...props} /><span>{label}</span></label>; }
export function Radio({ id, label, ...props }: InputHTMLAttributes<HTMLInputElement> & { id: string; label: string }) { return <label className="choice"><input id={id} type="radio" {...props} /><span>{label}</span></label>; }
export function ErrorSummary({ errors }: { errors: readonly { href: string; message: string }[] }) { return <section className="error-summary" role="alert" tabIndex={-1} aria-labelledby="error-summary-heading"><h2 className="type-h4" id="error-summary-heading">Check the highlighted fields</h2><ul>{errors.map((error) => <li key={error.href}><a href={error.href}>{error.message}</a></li>)}</ul></section>; }
